"""
This module is home to the Electricity class
"""
from .ecobee_object import EcobeeObject


class Electricity(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/Electricity.shtml

    Attribute names have been generated by converting ecobee property names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value of READONLY is "no".

    An __init__ argument without a default value has been generated if the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated if the value of REQUIRED is "no".
   """
    __slots__ = ['_devices']

    attribute_name_map = {'devices': 'devices'}

    attribute_type_map = {'devices': 'List[ElectricityDevice]'}

    def __init__(self, devices=None):
        """
        Construct an Electricity instance
        """
        self._devices = devices

    @property
    def devices(self):
        """
        Gets the devices attribute of this Electricity instance.

        :return: The value of the devices attribute of this Electricity instance.
        :rtype: List[ElectricityDevice]
        """

        return self._devices
