"""
This module is home to the MeterReportData class
"""
from pyecobee.ecobee_object import EcobeeObject


class MeterReportData(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/MeterReportData.shtml

    Attribute names have been generated by converting ecobee property names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value of READONLY is "no".

    An __init__ argument without a default value has been generated if the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated if the value of REQUIRED is "no".
   """
    __slots__ = ['_meter_type', '_columns', '_data']

    attribute_name_map = {'meter_type': 'meterType', 'meterType': 'meter_type', 'columns': 'columns', 'data': 'data'}

    attribute_type_map = {'meter_type': 'six.text_type', 'columns': 'six.text_type', 'data': 'List[six.text_type]'}

    def __init__(self, meter_type=None, columns=None, data=None):
        """
        Construct a MeterReportData instance
        """
        self._meter_type = meter_type
        self._columns = columns
        self._data = data

    @property
    def meter_type(self):
        """
        Gets the meter_type attribute of this MeterReportData instance.

        :return: The value of the meter_type attribute of this MeterReportData instance.
        :rtype: six.text_type
        """

        return self._meter_type

    @property
    def columns(self):
        """
        Gets the columns attribute of this MeterReportData instance.

        :return: The value of the columns attribute of this MeterReportData instance.
        :rtype: six.text_type
        """

        return self._columns

    @property
    def data(self):
        """
        Gets the data attribute of this MeterReportData instance.

        :return: The value of the data attribute of this MeterReportData instance.
        :rtype: List[six.text_type]
        """

        return self._data
