"""
This module is home to the Reminder class
"""
from pyecobee.ecobee_object import EcobeeObject


# class ThermostatReminder2(EcobeeObject):
class Reminder(EcobeeObject):

    """
    Attribute names have been generated by converting ecobee property names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value of READONLY is "no".

    An __init__ argument without a default value has been generated if the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated if the value of REQUIRED is "no".
    """

    __slots__ = [
        "_type",
        "_title",
        "_description",
        "_reminder_date",
        "_remind_me",
    ]

    attribute_name_map = {
        "type": "type",
        "title": "title",
        "description": "description",
        "reminder_date": "reminderDate",
        "reminderDate": "reminder_date",
        "remind_me": "remindMe",
        "remindMe": "remind_me",
    }

    attribute_type_map = {
        "type": "six.text_type",
        "title": "six.text_type",
        "description": "six.text_type",
        "reminder_date": "six.text_type",
        "remind_me": "bool",
    }

    def __init__(
        self, type_, title=None, description=None, reminder_date=None, remind_me=None
    ):
        """
        Construct a Reminder instance
        """
        self._type = type_
        self._title = title
        self._description = description
        self._reminder_date = reminder_date
        self._remind_me = remind_me

    @property
    def type(self):
        """
        Gets the type attribute of this Reminder instance.

        :return: The value of the type attribute of this Reminder instance.
        :rtype: six.text_type
        """

        return self._type

    @property
    def title(self):
        """
        Gets the title attribute of this Reminder instance.

        :return: The value of the title attribute of this Reminder instance.
        :rtype: six.text_type
        """

        return self._title

    @property
    def description(self):
        """
        Gets the description attribute of this Reminder instance.

        :return: The value of the description attribute of this Reminder instance.
        :rtype: six.text_type
        """

        return self._description

    @property
    def reminder_date(self):
        """
        Gets the reminder_date attribute of this Reminder instance.

        :return: The value of the reminder_date attribute of this Reminder instance.
        :rtype: six.text_type
        """

        return self._reminder_date

    @property
    def remind_me(self):
        """
        Gets the remind_me attribute of this Reminder instance.

        :return: The value of the remind_me attribute of this Reminder instance.
        :rtype: bool
        """

        return self._remind_me
