"""
This module is home to the RemoteSensorCapability class
"""
from pyecobee.ecobee_object import EcobeeObject


class RemoteSensorCapability(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/RemoteSensorCapability.shtml

    Attribute names have been generated by converting ecobee property names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value of READONLY is "no".

    An __init__ argument without a default value has been generated if the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated if the value of REQUIRED is "no".
   """
    __slots__ = ['_id', '_type', '_value']

    attribute_name_map = {'id': 'id', 'type': 'type', 'value': 'value'}

    attribute_type_map = {'id': 'six.text_type', 'type': 'six.text_type', 'value': 'six.text_type'}

    def __init__(self, id=None, type=None, value=None):
        """
        Construct a RemoteSensorCapability instance
        """
        self._id = id
        self._type = type
        self._value = value

    @property
    def id(self):
        """
        Gets the id attribute of this RemoteSensorCapability instance.

        :return: The value of the id attribute of this RemoteSensorCapability instance.
        :rtype: six.text_type
        """

        return self._id

    @property
    def type(self):
        """
        Gets the type attribute of this RemoteSensorCapability instance.

        :return: The value of the type attribute of this RemoteSensorCapability instance.
        :rtype: six.text_type
        """

        return self._type

    @property
    def value(self):
        """
        Gets the value attribute of this RemoteSensorCapability instance.

        :return: The value of the value attribute of this RemoteSensorCapability instance.
        :rtype: six.text_type
        """

        return self._value
