"""
This module is home to the Status class
"""
from pyecobee.ecobee_object import EcobeeObject


class Status(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/Status.shtml

    Attribute names have been generated by converting ecobee property
    names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value
    of READONLY is "no".

    An __init__ argument without a default value has been generated if
    the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated
    if the value of REQUIRED is "no".
    """

    __slots__ = ['_code', '_message']

    attribute_name_map = {'code': 'code', 'message': 'message'}

    attribute_type_map = {'code': 'int', 'message': 'six.text_type'}

    def __init__(self, code=None, message=None):
        """
        Construct a Status instance
        """
        self._code = code
        self._message = message

    @property
    def code(self):
        """
        Gets the code attribute of this Status instance.

        :return: The value of the code attribute of this Status
        instance.
        :rtype: int
        """

        return self._code

    @property
    def message(self):
        """
        Gets the message attribute of this Status instance.

        :return: The value of the message attribute of this Status
        instance.
        :rtype: six.text_type
        """

        return self._message
