"""
This module is home to the Utility class
"""
from pyecobee.ecobee_object import EcobeeObject


class Utility(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/Utility.shtml

    Attribute names have been generated by converting ecobee property names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value of READONLY is "no".

    An __init__ argument without a default value has been generated if the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated if the value of REQUIRED is "no".
   """
    __slots__ = ['_name', '_phone', '_email', '_web']

    attribute_name_map = {'name': 'name', 'phone': 'phone', 'email': 'email', 'web': 'web'}

    attribute_type_map = {'name': 'six.text_type', 'phone': 'six.text_type', 'email': 'six.text_type',
                          'web': 'six.text_type'}

    def __init__(self, name=None, phone=None, email=None, web=None):
        """
        Construct an Utility instance
        """
        self._name = name
        self._phone = phone
        self._email = email
        self._web = web

    @property
    def name(self):
        """
        Gets the name attribute of this Utility instance.

        :return: The value of the name attribute of this Utility instance.
        :rtype: six.text_type
        """

        return self._name

    @property
    def phone(self):
        """
        Gets the phone attribute of this Utility instance.

        :return: The value of the phone attribute of this Utility instance.
        :rtype: six.text_type
        """

        return self._phone

    @property
    def email(self):
        """
        Gets the email attribute of this Utility instance.

        :return: The value of the email attribute of this Utility instance.
        :rtype: six.text_type
        """

        return self._email

    @property
    def web(self):
        """
        Gets the web attribute of this Utility instance.

        :return: The value of the web attribute of this Utility instance.
        :rtype: six.text_type
        """

        return self._web
