"""
This module is home to the Version class
"""
from pyecobee.ecobee_object import EcobeeObject


class Version(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/Version.shtml

    Attribute names have been generated by converting ecobee property names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value of READONLY is "no".

    An __init__ argument without a default value has been generated if the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated if the value of REQUIRED is "no".
   """
    __slots__ = ['_thermostat_firmware_version']

    attribute_name_map = {'thermostat_firmware_version': 'thermostatFirmwareVersion',
                          'thermostatFirmwareVersion': 'thermostat_firmware_version'}

    attribute_type_map = {'thermostat_firmware_version': 'six.text_type'}

    def __init__(self, thermostat_firmware_version=None):
        """
        Construct a Version instance
        """
        self._thermostat_firmware_version = thermostat_firmware_version

    @property
    def thermostat_firmware_version(self):
        """
        Gets the thermostat_firmware_version attribute of this Version instance.

        :return: The value of the thermostat_firmware_version attribute of this Version instance.
        :rtype: six.text_type
        """

        return self._thermostat_firmware_version
